### PR TITLE
Changed create wallet to create key

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**

### CODE REVIEW

**Review by mustafapylons — COMMENTED** [review]
Create key is "Schlussel erstellen" in German.

**Comment by heyitsjk** [comment]
> 

that was my bad, confused DE with Dutch when I was moving quickly on those 🤦🏻‍♂️

**Comment by kjawadDeveloper2** [comment]
@heyitsjk  whats the correct translation then?

**Comment by heyitsjk** [comment]
@kjawadDeveloper2 Create Key in German, it is "Schlüssel Erstellen"

**Review by faddat — APPROVED** [review]

**Review by mustafapylons — APPROVED** [review]
Looks good to me now.

**Pull request merged**
