### PR TITLE
Resolved the issue with easel build

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**
Disabled shrinking on easel. 
Solved stripe issue.

### CODE REVIEW

**Comment by kjawadDeveloper2** [comment]
Need to add some tests.

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by kjawadDeveloper2** [comment]
Added tests. @faizhashmiRnS  These kinds of test we should implement.

**Review by Amean — APPROVED** [review]

**Comment by faizhashmiRnS** [comment]
> Added tests. @faizhashmiRnS These kinds of test we should implement.

@ahmadrns please review these tests.

**Pull request merged**
