### PR TITLE
Test cases was added for AfterEpochEnd function

### PR DESCRIPTION
**Pull request by AbdulSamad876**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by Tanyaml** [comment]
Not QA testable.

**Review by MikeSofaer — COMMENTED** [review]
Doesn't this show that delegators are not being paid?

**Review by kjawadDeveloper2 — APPROVED** [review]

**Comment by faisalnaveedRNS** [comment]
1. artist distribution
2. validator distribution
3. bedrock holder distribution (deligators)

**Comment by faisalnaveedRNS** [comment]
Test cases should cover specially token encomics

**Comment by StefanB90** [comment]
Refactor test case to make it more readable. Focus on executable test.

**Review by MikeSofaer — CHANGES_REQUESTED** [review]
This test is relying on the CalculateDelegatorsRewards to create the list of people who should be paid out, I would like it to instead get the list of Bedrock holders and validators from the chain and use that to iterate. The current method is checking against itself a little too much.

**Comment by Tanyaml** [comment]
Show that people are getting paid and see how the the tokens work as intended @faisalnaveedRNS

**Review by MikeSofaer — APPROVED** [review]

**Pull request merged**
