### PR TITLE
Feat/create

### PR DESCRIPTION
**Pull request by afti-githobo**
## Description

Implements devtool create command.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by faddat** [comment]
oh, your commit messages, are like mine.

**Comment by faddat** [comment]
hey :).

Just wanted to follow up and let you know that we can set up a time to talk today.

**Comment by afti-githobo** [comment]
> hey :).
> 
> Just wanted to follow up and let you know that we can set up a time to talk today.

has to be immediately after standup; it's the only window we're both gonna be awake long enough to go over it

**Comment by afti-githobo** [comment]
closing for omnibus

**Comment by faddat** [comment]
ah ok

**Comment by faddat** [comment]
for the omnibus, I recommend that you make the 46 branch the target-- we really should just merge 46 to main now, but I just can't:

2 approving non-me reviews are needed.

**Pull request closed without merging**
