### PR TITLE
Testapp flutter

### PR DESCRIPTION
**Pull request by afti-githobo**
## Description

Implements a Flutter version of the testapp frontend for Android. (IOS support will have to come later; I don't have a viable IOS development platform.)

Note that there are outstanding questions about how to actually implement certain behaviors with the Dart SDK that need to be resolved before this will actually be good for anything - probably tomorrow?

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by afti-githobo** [comment]
tagging in @kjawadDeveloper2 since this is still unresolved and i still have the following open questions abt use of the dart sdk

a) how do we get the tx hash back from TxExecuteRecipe?
b) how do we get a tx back by hash?
c) it seems like `getExecutionById` just returns tx data - how do we actually check whether an execution has finished, then?

**Comment by StefanB90** [comment]
if everything successful there will be a transaction hash... otherwise it will return an error.

**Comment by afti-githobo** [comment]
> if everything successful there will be a transaction hash... otherwise it will return an error.

Hold on, this doesn't make sense. How is this actually supposed to work? Per the documentation the data field on `txExecuteRecipe` is still just a profile, which... does not include the tx hash. Either it doesn't return a hash at all, or it returns a hash in a structure that isn't a profile, but I don't know what that'd be because the documentation doesn't say so.

I also still need input on the other two questions here.

**Comment by MikeSofaer** [comment]
These are good questions, but they really highlight a deeper problem, as I said last week. We need to give the SDK a higher-level interface so that developers don't need to even ask these questions.

`execution = cookbook.recipe(recipeId).execute_with(item1: item_id, item2:item_id)
execution.success = function(results)
execution.failure = function.error`

Something like that. We have to make this super super easy for devs.

**Comment by afti-githobo** [comment]
> These are good questions, but they really highlight a deeper problem, as I said last week. We need to give the SDK a higher-level interface so that developers don't need to even ask these questions.
> 
> `execution = cookbook.recipe(recipeId).execute_with(item1: item_id, item2:item_id) execution.success = function(results) execution.failure = function.error`
> 
> Something like that. We have to make this super super easy for devs.

I don't dispute this, but making major API changes doesn't really help me get this done *right now.* (On that note: having dynamically typed fields on the responses *at all* is a needless source of friction; it should be easy to look at the code and know exactly what data you're getting back)

**Comment by kjawadDeveloper2** [comment]
@afti-githobo  best way to check the working of the sdk is to check its example folder. It has an flutter app with all the transactions that sdk supports. Using the example app will give you insights of the sdk.

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/tree/main/dart_sdk/example

This is the example app. 

Clone the whole code and open example app as a flutter project.

**Comment by afti-githobo** [comment]
> https://github.com/Pylons-tech/pylons/tree/main/dart_sdk/example
> 
> This is the example app.
> 
> Clone the whole code and open example app as a flutter project.

I'm aware of the example app, but the example app doesn't do anything useful to elucidate any behavior I can't just get from reading the code. If I could answer these questions by looking over the example app I would not have asked them.

**Comment by MikeSofaer** [comment]
@kjawadDeveloper2 let's schedule a meeting to go over required changes in the SDK if this thread does not make them clear.

**Comment by afti-githobo** [comment]
Also, digging through the wallet to try and figure things out now and I'm getting the impression there isn't actually an SDK call that exposes the low-level get-TX-by-hash functionality?

This is a problem at present. We need to be able to get the ID of a specific newly created item and (unless this behavior has been fixed w/o my knowledge) the `itemsCreated` field you get back after TX execution has bad data.

**Comment by kjawadDeveloper2** [comment]
So now create cookbook will return cookbook . https://github.com/Pylons-tech/pylons/pull/1054

**Comment by afti-githobo** [comment]
> So now create cookbook will return cookbook . #1054

what does that have to do w/ this pr?

**Comment by MikeSofaer** [comment]
> > So now create cookbook will return cookbook . #1054
> 
> what does that have to do w/ this pr?

Well, it's a step towards better responses. Next up is create_receipe returning recipe, and then execute_recipe returning recipe_execution

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/pull/1062 @afti-githobo  you will get recipe now.

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/pull/1090 @afti-githobo  you will now get executions.

**Comment by kjawadDeveloper2** [comment]
@afti-githobo  do you need anything from me?

**Comment by afti-githobo** [comment]
> @afti-githobo do you need anything from me?

Not here, but if you have some time to comment on what's happening in 1091 that'd be appreciated.

**Pull request closed without merging**
