### PR TITLE
Added firebase remote config flag for stripe

### PR DESCRIPTION
**Pull request by kjawadDeveloper**
We can now remotely control the stripe for the ios.

### CODE REVIEW

**Comment by kjawadDeveloper** [comment]
This will solve this. 
https://github.com/Pylons-tech/pylons/issues/931

**Comment by MikeSofaer** [comment]
This needs to be a flag on the recipe, not a flag for the whole app, sorry for the confusion. The idea is that we can sell tickets and t-shirts with Stripe, but not art.

**Comment by kjawadDeveloper2** [comment]
@MikeSofaer its only for recipe right now.

**Comment by MikeSofaer** [comment]
This needs to be per-recipe.

Easel recipes -> No flag, cannot use Stripe on iOS
Evently recipes for virtual events -> No flag, cannot use Stripe on iOS
Evently recipes for physical events -> Flag is set, Stripe can be used on iOS

**Comment by kjawadDeveloper2** [comment]
It will be like this. But right now evently is not fully implemented. When it will be we can then review these conditions.

**Comment by faddat** [comment]
could you please resolve the conflicts?

**Review by faddat — APPROVED** [review]

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by faddat** [comment]
I just did the conflict resolution, I may have gotten it wrong.  If it builds, I'll merge.

**Pull request closed without merging**
