### PR TITLE
Added events based on screen in easel

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**

### CODE REVIEW

**Comment by heyitsjk** [comment]
For the "Analytics Failure" i18n, lets change this to: 

EN:
"analytics_failure" : "Analytics Error"
  
DE:
"analytics_failure" : "Analytics-Fehler"

ES:
"analytics_failure" : "Error de Análisis"

RU:
"analytics_failure" : "Ошибка аналитики"

**Comment by kjawadDeveloper2** [comment]
@heyitsjk  Added the translations that you provided.

**Comment by kjawadDeveloper2** [comment]
Added fix for this also https://github.com/Pylons-tech/pylons/issues/1199

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by heyitsjk** [comment]
analytics + i18n looks good to me

**Review by faisalnaveedRNS — APPROVED** [review]

**Pull request merged**
