### PR TITLE
table test driven for query payment_info

### PR DESCRIPTION
**Pull request by ThanhNhann**
## What is the purpose of the change
   - Write table-driven test code 
## Brief Changelog
   - Write all cli test cases with table-driven test for `CmdShowPaymentInfo` and `CmdListPaymentInfo`function 
## Testing and Verifying
   - This change is a trivial rework/code cleanup without any test coverage
## Documentation and Release Note
   - Does this pull request introduces a new feature or user-facing behaviour changes? no 
   - How is the feature or change documented? not applicable
## Notional-labs

---

### CODE REVIEW

**Review by faddat — APPROVED** [review]

**Review by faddat — CHANGES_REQUESTED** [review]
@ThanhNhann hey, this causes tests to fail.  Can you please dig into that?  Maybe the tested code has changed a bit. 

The tests that you guys are writing are straight 🔥

**Review by faddat — APPROVED** [review]

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by ThanhNhann** [comment]
Thank sir @faddat , I saw the fail in the test of keeper not of this, will be fixed asap

**Comment by ThanhNhann** [comment]
Hi sir @faddat, I think the error from the code of `SetPylonsAccount`, I created the pr to fix that error, pls check and merge  https://github.com/Pylons-tech/pylons/pull/995

**Pull request merged**
