### PR TITLE
Example project for dev tools

### PR DESCRIPTION
**Pull request by afti-githobo**
## Description

Implements an example project for the dev tools.

I want to do more tinkering w/ these to make them explain what they're doing better and introduce a lil more complexity to flex the module system; don't merge this yet.

@faddat - can you drop the stuff you mentioned about spinning up a testnet in the comments? I wanna make sure you can actually create/update the example recipes and they do what they're supposed to before they're a significant part of the documentation.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by faddat** [comment]
pylonsd testnet start --enable-logging

**Comment by afti-githobo** [comment]
> pylonsd testnet start --enable-logging

oh. that's much less involved than the impression I got this morning, lol.. don't know how that'd intersect w/ automated tests tho?

**Comment by faddat** [comment]
Concerning the automated tests, it is possible (maybe not the right approach and will vary situationally) two fair transactions into that test net and it's actually a better test and faster in some cases. Please keep in mind that some of this will involve sort of looking at what it does when it sets up that testnet, realizing that OK it's a real tennis net, what do I do from here

Sorry to be vague, but it is a little bit vauge

**Review by faddat — APPROVED** [review]
this looks great!

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Pull request merged**
