### PR TITLE
refactor proto compliance

### PR DESCRIPTION
**Pull request by nghuyenthevinh2000**
## Description

Closes: #607 

This pull request moves pylons and epochs proto folder to under pylons folder. This is in compliance with the rest of cosmos ecosystem for tool integration.

1. Add lint rule in buf.yaml in proto folder for warning cases in proto files
2. Add proto engine based on container tendermintdev/sdk-proto-gen:v0.7 and remove starport proto-go. No one uses starport anymore, it is now ignite.
3. Why is there a buf.yaml file in / . Rather redundand or it is there for a meaning? @aljo242 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
It is not my fault that the final test fails. It is already failing in main.
Screenshot from 2022-06-29 09-15-58

**Comment by faddat** [comment]
@nghuyenthevinh2000 it's everyone's fault-- let's fix it :)

**Review by faddat — APPROVED** [review]
Approved with one request for a change:

can you please put in readme.md the preferred way to rebuild protobufs?

Actually, I'm concerned that this PR did break it?

Not certain.

**Comment by nghuyenthevinh2000** [comment]
> Approved with one request for a change:
> 
> can you please put in readme.md the preferred way to rebuild protobufs?
> 
> Actually, I'm concerned that this PR did break it?
> 
> Not certain.

the preferred way is to use tendermintdev/sdk-proto-gen:v0.7 container then build proto with buf inside that container. This way we can control how it is built with the same container environment for all types of machine.

using startport generate proto-go is ancient since it has changed to newer version of ignite. Besides, each machines can be different leading to different version of startport used for proto build. 

@faisalnaveedRNS can we discuss on this? I want to make sure all devs remember proto rules so as to use snake_case.

**Comment by faddat** [comment]
wooooo gosh I hate protos.  Let me check through the readme on rebuilding them, then I think after a rebuild this is ready to merge. 

Thanks so much for your work on this vinh.

**Comment by pyramation** [comment]
thank you so much @nghuyenthevinh2000 this is great work 🙌🏻

**Review by faisalnaveedRNS — APPROVED** [review]
approved

**Comment by faddat** [comment]
**much excite!**

**Comment by faddat** [comment]
I'll let these tests run, then merge.  Thank you Vinh!

**Pull request merged**
