### PR TITLE
v46

### PR DESCRIPTION
**Pull request by faddat**
## Description

The cosmos sdk has bumped tendermint down to 34 successfully, and this branch is based on the first public release of that work, tracked to be merged into cosmos-sdk v46 and released as final.  This work is accompanied by version 46 upgrades to ibc-go v4 and CosmWasm's wasmd v0.28.0

https://github.com/cosmos/ibc-go/pull/1653

This branch is "ready to ship" to a testnet as soon as it greenifies.

I don't think we'll add cw on this release, though that can be a topic for today's call. 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MikeSofaer** [comment]
I thought you were boycotting gitpod

**Comment by faddat** [comment]
gitpod team members reached out to me, and they've removed themselves from the madness letter.

**Comment by MikeSofaer** [comment]
legendary

**Comment by vuong177** [comment]
@faddat, how about ics-721-nft-transfer. Should we make pylons NFT can be transfer over IBC ?

**Comment by faddat** [comment]
not in this build, I think

**Comment by nghuyenthevinh2000** [comment]
I need to get #611 done first because it is related to proto generation as well. Need to convert from sdk.Dec to sdk.Int so as to be compatible with math.Int. v46 has largely moved to math.Int.

starport generate proto-go cannot generate sedly

**Comment by faddat** [comment]
@nghuyenthevinh2000 hey, so I pure-merged your work here, so that we can work from this single branch. Thank you!

**Pull request closed without merging**
