### PR TITLE
Added bottom sheet when no pylons app found

### PR DESCRIPTION
**Pull request by ahmadrns**
This PR Solves this issue: https://github.com/Pylons-tech/pylons/issues/1400

Need to handle when user don't accept `Accept Policy` & `Term & Services` in wallet app and also remove check of `No wallet created`.

### CODE REVIEW

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/206172250-69da9900-f988-40f2-99c0-5b9db3cbf3ba.mov

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/206172472-4090b24b-bc02-4849-a17c-934792831b87.mp4

**Comment by ahmadrns** [comment]
@kjawadDeveloper2  We need to update the pylons SDK go get whether or not user accepted the Term and Service & Privacy Policy in Wallet app

**Comment by ahmadrns** [comment]
Untitled

**Comment by MikeSofaer** [comment]
@kjawadDeveloper2 should we merge this?

**Pull request closed without merging**
