### PR TITLE
Resolved issues that was blocking the build

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**
1) Resolved language issue. 
2) Resolved nft autoclose issue. 
3) Resolved easel status issue. 
4) Added forced redirection in the deep links
.

### CODE REVIEW

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/issues/1016

**Comment by faisalnaveedRNS** [comment]
@mustafapylons better comment on this

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/issues/1005

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/issues/1015

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by kjawadDeveloper2** [comment]
@heyitsjk resolved in this. https://github.com/Pylons-tech/pylons/issues/1024

**Comment by kjawadDeveloper** [comment]
https://github.com/Pylons-tech/pylons/issues/846

@heyitsjk

**Review by faddat — APPROVED** [review]

**Pull request merged**
