### PR TITLE
Delete deployprotos.yml

### PR DESCRIPTION
**Pull request by faddat**
## Description

dead test relying on obsolete credentials

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MikeSofaer** [comment]
We need to include proto updating in this repo as we remove it from the remote repo, assuming that's not already happening.

**Comment by faddat** [comment]
Mike, what I'd prefer to do here, is add the protobufs to a linting check, to ensure that they're not broken.  I am not fully sure what you mean here by proto updating, since changes to the protos would prevent a successful build (not in the .proto files, but instead in the .pb.go files)

**Comment by MikeSofaer** [comment]
It's about making sure the Pylons mobile app (which is closed source) updates cleanly with the chain. But maybe we don't need to do anything for that.

**Comment by faddat** [comment]
We shouldn't-- check out this:

https://github.com/Pylons-tech/pylons/blob/247aae9e23c97fa64c83ccb4883ad115485f11d1/x/pylons/types/payment_info.pb.go

**Comment by MikeSofaer** [comment]
In the interest of speed, OK.

**Review by faisalnaveedRNS — APPROVED** [review]
this look fine, as we are moving away from ignite we dont need this

**Pull request merged**
