### PR TITLE
Change sale status using toggle(updated) issue #1298

### PR DESCRIPTION
**Pull request by Kamran-Khan-Gene**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MikeSofaer** [comment]
The last screenshot doesn't make a lot of sense. We are supposed to be using Pylons Credit, like `$10.00 Pylons Credit`

**Comment by Kamran-Khan-Gene** [comment]
> The last screenshot doesn't make a lot of sense. We are supposed to be using Pylons Credit, like `$10.00 Pylons Credit`

@MikeSofaer there is a dropdown button in the Figma. I thought that a dropdown button using which user can select from different options (Pylons & USD). 

If I am mistaken kindly let me know its flow so I can work on it accordingly. 

image

**Comment by Kamran-Khan-Gene** [comment]
@faisalnaveedRNS @MikeSofaer 

what does this 100 USD represent? is it static?


image

**Comment by MikeSofaer** [comment]
This should go back to design, I think. It should be "Pylons Credit" not Pylons Points, and they should be shown with $, and not need an equivalence section.

**Comment by kjawadDeveloper2** [comment]
@StefanB90

**Comment by StefanB90** [comment]
@kjawadDeveloper2 

https://github.com/Pylons-tech/pylons/issues/1348
https://github.com/Pylons-tech/pylons/issues/1349

**Pull request closed without merging**
