### PR TITLE
Improvement: Added the platform based abstraction for the dart sdk

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**
1) Added platform based abstraction. 
2) Updated the tests

### CODE REVIEW

**Review by afti-githobo — APPROVED** [review]

**Comment by afti-githobo** [comment]
@kjawadDeveloper2 can you fix those linter issues?

@MikeSofaer @Amean  @faisalnaveedRNS can we get more reviews on this? i would like it to be merged tomorrow if possible; it should def. improve the ux for testapp and (given how Spooky the double future exec issue is and how much this changes) it might even incidentally address that; idk.

**Review by MikeSofaer — APPROVED** [review]
This seems fine to the extent that I understand it, but there's something weird about the Completer situation, it's like maybe the object lives too high up the chain, and that's why there's data pollution risk, and it should be a lower level thing like a Completion or something. I am aware that I don't really know what I'm talking about here.

**Review by Amean — COMMENTED** [review]
Should you fix the check failure?

**Comment by kjawadDeveloper2** [comment]
> Should you fix the check failure?

Unfortunately it was go issue.

**Pull request merged**
