### PR TITLE
Added File extension on Chain (Easel & Wallet)

### PR DESCRIPTION
**Pull request by ahmadrns**
Issue mentioned in: https://github.com/Pylons-tech/pylons/issues/1462

### CODE REVIEW

**Comment by ahmadrns** [comment]
image

**Comment by Tanyaml** [comment]
@Amean @afti-githobo Please review.

**Review by Amean — APPROVED** [review]

**Comment by heyitsjk** [comment]
unnamed-15

@ahmadrns what is the Easel icon? Shouldn't this be the download icon? @StefanB90 

Figma Design:
Full screen NFT view (pop-up maximized) (1)

**Comment by ahmadrns** [comment]
@heyitsjk I just get the latest code from main and add the extension functionality about the issue and make PR. I will look into the design changes too and refactor code accordingly.

**Comment by ahmadrns** [comment]
@heyitsjk This icon is for setting wallpaper in case of image NFT

**Comment by ahmadrns** [comment]
@heyitsjk As discussed with @Kamran-Khan-Gene download feature is implemented but not merge yet as it has some blockers so can I remove wallpaper icon and add views Icons on top of like icon?.

**Comment by heyitsjk** [comment]
@ahmadrns ah that makes sense, if the wallpaper feature is ready to go then that could sit there for now until we're ready to add download and move the icons around. @StefanB90 

wallpaper feature is Android-only, correct? Since iOS can not set user device wallpaper natively

**Comment by ahmadrns** [comment]
@heyitsjk Okay for now leaving it as it is and when we need to add Download feature then we will arrange icons and also remove this wallpaper icon too
Yes, this is for Android only.

**Pull request merged**
