### PR TITLE
fix: sku was updated

### PR DESCRIPTION
**Pull request by faisalnaveedRNS**
## Description

Closes: #1036

SKU was added

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by mustafapylons** [comment]
@jlkershner these are the SKUs going in based on what we discussed yesterday. I talked to @heyitsjk as well and is the list below enough for now:

{PackageName: "tech.pylons.wallet", ProductId: "pylons_10", Amount: sdk.NewInt(10000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_30", Amount: sdk.NewInt(30000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_35", Amount: sdk.NewInt(35000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_50", Amount: sdk.NewInt(50000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_60", Amount: sdk.NewInt(60000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_100", Amount: sdk.NewInt(100000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_500", Amount: sdk.NewInt(500000000)},
                {PackageName: "tech.pylons.wallet", ProductId: "pylons_1000", Amount: sdk.NewInt(1000000000)},

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 can you please add these in google and apple pay,

**Comment by jlkershner** [comment]
> @jlkershner these are the SKUs going in based on what we discussed yesterday. I talked to @heyitsjk as well and is the list below enough for now:
> 
> {PackageName: "tech.pylons.wallet", ProductId: "pylons_10", Amount: sdk.NewInt(10000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_30", Amount: sdk.NewInt(30000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_35", Amount: sdk.NewInt(35000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_50", Amount: sdk.NewInt(50000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_60", Amount: sdk.NewInt(60000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_100", Amount: sdk.NewInt(100000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_500", Amount: sdk.NewInt(500000000)}, {PackageName: "tech.pylons.wallet", ProductId: "pylons_1000", Amount: sdk.NewInt(1000000000)},

Michael: The SKUs that Jordan picked out were 10, 65, and 110.  We need those included and only 10 is in your list.
Old:
10 for $0.99
35 for $2.99
60 for $4.99

New:
10 for $0.99
65 for $5.99
110 for $9.99

**Comment by MikeSofaer** [comment]
Yes, please add the 65 and 110 SKUs for @heyitsjk.

Please also make sure we have SKUs at around 10K and 100k Pylons. Just in case someone wants to spend a lot of money.

**Review by faddat — APPROVED** [review]
STATE BREAKING CHANGE (a good one though)

**Pull request merged**
