### PR TITLE
Ps484update

### PR DESCRIPTION
**Pull request by Amean**
Finishing service and dependency fixes for Pylons App Widget https://github.com/Pylons-tech/pylons/issues/837

### CODE REVIEW

**Comment by faddat** [comment]
no one knows what ps484 is, please link to the github issue being resolved.

**Comment by heyitsjk** [comment]
PS-484 refers to the old JIRA task for this feature:

Pylons App Widget #837

**Review by faddat — APPROVED** [review]

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 please look in to this

**Comment by kjawadDeveloper2** [comment]
@Amean  can you give me a demo?

**Review by kjawadDeveloper2 — CHANGES_REQUESTED** [review]
Until demo is not shown i cannot merge it.

**Pull request closed without merging**
